spring:
  application:
    name: meeting-assistant-bot

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework.boot.actuator: DEBUG